### ISSUE TITLE
use shallow clone for gitarro 

### ISSUE THREAD

**Issue by MalloZup** [openSUSE/gitarro#107]
Using shallow clones will remove/refactor the code and we will remove the mandatory G option.

Additionally we will be more safe, avoiding conflict errors and artifacts. since we will remove

**Comment by MalloZup** [comment]
https://github.com/openSUSE/gitarro/issues/104

**Comment by MalloZup** [comment]
a) Shallow clone
 b) Use an external repo
 external , that already contains a git repo
, that's useful if the user wants to manage git with jenkins or any other tool
a) you will need a way to let the user to specify the place to clone
tmp is fine by default, as long as you add a parameter (or reuse an existing one) to specify another

**Comment by juliogonzalez** [comment]
In fact my idea was:

a) Shallow clone (remember we won't be able to merge changes from the upstream branch, but that's fine we should test exactly the commit that the PR sent, without changing anything).
b) Allow specifying a place to clone, being /tmp/gitbot/girepo-YYYYMMDD-HHMMSS-mmm (mmm = miliseconds) the default
c) Show an ERROR and exit if the directory where the clone will be hosted exists
d) Remove the directy by default, but add an option to keep it (for people that wants to have a look at Jenkins job workspace or archive the repo state, or whatever other needs).
