### ISSUE TITLE
Gitarro is not able to handle merge problems

### ISSUE THREAD

**Issue by juliogonzalez** [openSUSE/gitarro#108]
```
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
```

In this situation gitarro exists (correct) with a return value !=0 (correct), but it does not show any error or updates the PR test status at GitHub, leaving it as 'pending' forever.

**Comment by juliogonzalez** [comment]
Check if gitarro is exiting with != 0 because of an exception, or if it is a controlled exit.

**Comment by MalloZup** [comment]
ok thx!

**Comment by MalloZup** [comment]
fixed by shallow clone
