### ISSUE TITLE
gitarro exception causes a PR gets stuck in pending

### ISSUE THREAD

**Issue by meaksh** [openSUSE/gitarro#111]
I'm having some issues with gitarro on this PR: https://github.com/SUSE/spacewalk/pull/2515

It seems that `gitarro` starts the execution for that PR but then get some exception and the PR gets stuck in `pending` state.

Either running a manual `rerun` command or force pushing the PR to recreate last commit don't work. It leads into the same problem again.

I've caught this exception on Jenkins during gitarro execution: https://ci.suse.de/view/Manager/view/Manager-prs/job/manager-prs-backend_psql-pipeline/219/console

**Comment by MalloZup** [comment]
@meaksh  thank you. it seems that the file doesn't exist, i think there is a problem with the pipeline.
```
/home/jenkins/jenkins-build/workspace/manager-prs-backend_psql-pipeline/spacewalk/susemanager-utils/testing/automation/backend-unittest-pgsql.sh
```

**Comment by meaksh** [comment]
Thanks for taking a look to this @MalloZup ! 👍

**Comment by MalloZup** [comment]
@meaksh thank a lot for your report. The pipeline is here,  https://github.com/SUSE/susemanager-ci

https://github.com/SUSE/susemanager-ci/pulls

**Comment by MalloZup** [comment]
@meaksh  i will move the issue to https://github.com/SUSE/susemanager-ci/issues/6, i think i already fixed  it. feel free to report any other anomalies! i will wait for you next contribution on golang soon  ( i am plaining to do something in golang or elixir :D )D
