### ISSUE TITLE
gitarro does not mark tests as failed at GitHub if it's not able to clone  a forked private repository

### ISSUE THREAD

**Issue by juliogonzalez** [openSUSE/gitarro#113]
https://ci.suse.de/job/manager-prs-schema-migration-pipeline/3947/console

It failed the test at Jenkins (OK), but the PR was not updated: https://github.com/SUSE/spacewalk/pull/2665#pullrequestreview-78753789

**Comment by MalloZup** [comment]
closing because this was an issue specific to github user credentials:

https://github.com/SUSE/spacewalk/pull/3225

**Comment by juliogonzalez** [comment]
Reopening, because there is a bug yet.

If the clone fails, the test must be marked as failed at GitHub, and right now it stays "running forever".

**Comment by juliogonzalez** [comment]
Hapenning again at https://ci.suse.de/job/manager-tests-pipe/26790/console

**Comment by MalloZup** [comment]
@juliogonzalez  do we fixed this or not? with the latest PR?

**Comment by juliogonzalez** [comment]
@MalloZup I am not sure.

I would say yes, but I'd need to test it. For that I need a special cloned private repository with the inherited permissions removed it, so let's keep it for a while, until I can verify it.

**Comment by MalloZup** [comment]
@juliogonzalez  ok thx  ! :boat:

**Comment by MalloZup** [comment]
@juliogonzalez i am optimistic so i close this, and feel free to reopen in case opposite
