### ISSUE TITLE
Changelog test does not fail Jenkins builds when it fails

### ISSUE THREAD

**Issue by juliogonzalez** [openSUSE/gitarro#114]
https://ci.suse.de/job/manager-prs-changelog-pipeline/7402/console

Is it maybe returning an in correct return code (0) to the system?

But it does marks the test as failed at the PR: https://github.com/SUSE/spacewalk/pull/2725#pullrequestreview-79817891

**Comment by MalloZup** [comment]
@juliogonzalez  thx, this is more a pipeline issue then a gitarro one, moving to susemanager-ci

**Comment by MalloZup** [comment]
https://github.com/SUSE/susemanager-ci/issues/14
