### ISSUE TITLE
send-an-email to github author of PR in case of a failed tests

### ISSUE THREAD

**Issue by MalloZup** [openSUSE/gitarro#115]
We want to send results for failed tests to the github author of the PR.

**Comment by cavalheiro** [comment]
It would be interesting to include a way to "subscribe" for this feature on each PR (disabled by default).
My suggestion is something on the PR Template, a checkbox labelled something like "Get failure notifications for this PR on your email".

**Comment by MalloZup** [comment]
i am closing because we discussed it time ago.  thx
