### ISSUE TITLE
export ENV_Variable 

### ISSUE THREAD

**Issue by MalloZup** [openSUSE/gitarro#126]
this function is not called

that is why is not used by changelog test and is failing

https://github.com/openSUSE/gitarro/blob/660bc1379d8eeefcb1765301b7d51a090bc4e164/lib/gitarro/backend.rb#L131

TODO:

add the helper in the global function.

https://github.com/openSUSE/gitarro/blob/660bc1379d8eeefcb1765301b7d51a090bc4e164/lib/gitarro/backend.rb#L102

@juliogonzalez i would also as `nitpick` just rename the function ` export_pr_data_to_file`
in ` export_pr_data_to_jsonfile` or ` export_pr_data_to_json_file`

**Comment by juliogonzalez** [comment]
@MalloZup he only reason I did not do it that way is because that function is still exporting to the old file as well. I'd suggest keeping it as it is untill we can remove that.

**Comment by juliogonzalez** [comment]
Maybe `export_pr_data_to_files` in the meantime?

**Comment by juliogonzalez** [comment]
Agh, ignore me, I now see I added a separated function. Adding your suggestion :-)
