### ISSUE TITLE
Gitarro runs test even when the filter is not matched

### ISSUE THREAD

**Issue by juliogonzalez** [openSUSE/gitarro#132]
Example:

PR https://github.com/uyuni-project/uyuni/pull/176 was only changing files inside `schema/` but the test https://ci.suse.de/job/Uyuni-PRs/job/Uyuni-PRs-pgsql-pipeline/11971/ was executed (I enabled the option to keep the build forever, so please disable it when this problem is fixed).

That job runs https://github.com/SUSE/susemanager-ci/blob/master/jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_psql_unit where the filter is `java/`

So in theory gitarro should not detect https://ci.suse.de/job/Uyuni-PRs/job/Uyuni-PRs-pgsql-pipeline/11971/ requiring tests when `--check` is used, and even if that fails, it should not test.

**Comment by juliogonzalez** [comment]
It's weird but according to the help, `-f` should be used with file extensions, not directories:
```
    file_description = 'pr_file type to run the test against: .py, .rb'
``

**Comment by MalloZup** [comment]
This GitHub PR is unactive since more then 50 days. Is this GitHub PR still needed? Please close or update it accordingly.
         This reminder is autogenerated by https://github.com/MalloZup/blacktango

**Comment by juliogonzalez** [comment]
I think it still happens. But we'll need to have a second look @srbarrios, can you recall this problem lately?

**Comment by srbarrios** [comment]
Well, after the last changes in our team, on Jenkins Pipelines, yes was happening but is probably not related. So it was related to chain a first "check" with gitarro and then a second call to gitarro using --PR which was not filtering and re-triggering directly.

**Comment by MalloZup** [comment]
Thx oscar feel free to close
