### ISSUE TITLE
Documentation: go throught and fix typos or logical pb

### ISSUE THREAD

**Issue by MalloZup** [openSUSE/gitarro#144]
This is about the easiest fix ever :smile: 
Go through doc and fix logical errors or typos

**Comment by jatin69** [comment]
Hi, can i take this?

**Comment by MalloZup** [comment]
@jatin69  sure feel free to take experiment and open pr or issue! For any info ping me

**Comment by MalloZup** [comment]
Hi @jatin69 yop i would in your situation take all changes from upstream and rebase

**Comment by jatin69** [comment]
Hi @MalloZup I did my best to resolve all the conflicts. Please check it out.

**Comment by MalloZup** [comment]
i consider it more or less closed ( since i accepted already 2 prs ) and other reviewed it before. !

Many thx  :cupid:
