### ISSUE TITLE
Design new Logo for gitarro

### ISSUE THREAD

**Issue by MalloZup** [openSUSE/gitarro#150]
I admit, i am not a designer :smile: 

The challange would be to have something with Gundam, GIT and something funny. ( the octokit logo is kind of that).

We could think like a git-gundam looking like a rockstar like Metallica :guitar:

**Comment by ggabogarcia** [comment]
Hello, I found this and I would like to collaborate, this is my proposal I hope you like it.
# 
![robots](https://user-images.githubusercontent.com/35750428/46981341-82efda00-d09d-11e8-9b95-2ac86b76a5b6.jpg)

**Comment by MalloZup** [comment]
WooooooooHah! This is mega awesome! I will merge it send a pr with the logo ! Awesome thx

**Comment by MalloZup** [comment]
@ggabogarcia  i love it! feel free to send me a PR :cupid:

**Comment by ggabogarcia** [comment]
I am going to correct some details and then I create a PR, besides I will send you the editable files, PDF, EPS and SVG

**Comment by ggabogarcia** [comment]
Hello, I was thinking about placing this in the readme file, what do you think?
# 
![mesa de trabajo 1ldpi](https://user-images.githubusercontent.com/35750428/47037795-86d73700-d145-11e8-8028-f9d65b172a60.png)

**Comment by MalloZup** [comment]
Beautiful

**Comment by MalloZup** [comment]
I like it with colors also

**Comment by ggabogarcia** [comment]
I think I better send you the files hehe :smile_cat: 
# [Files](https://drive.google.com/drive/folders/1flJdjWXa9NtLVcn1DK1dWkG-08WHafci?usp=sharing) 
![DERECHOS.jpg](https://cdn.steemitimages.com/DQmVSH7hxt3nuyDxNRdWUBUBtfR11TyvLxM1F1C4vYW5UzG/DERECHOS.jpg)
This work is licensed under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/)
