### ISSUE TITLE
Use files for readme instead of weblink

### ISSUE THREAD

**Issue by MalloZup** [openSUSE/gitarro#152]
https://github.com/openSUSE/gitarro/pull/151 we need to use the file and updated them

**Comment by toshitapandey** [comment]
@MalloZup Can i pick it up? 

Also, I see that your readme is already using GIT links, what exactly is expected to be referenced?

**Comment by MalloZup** [comment]
@toshitapandey yop pick this up. Basically we need to create a dir putting the logo files and then use the link.to localpath

**Comment by MalloZup** [comment]
https://github.com/openSUSE/gitarro/issues/150#issuecomment-430355818

**Comment by MalloZup** [comment]
The files are there ,.so we need to create a logo and dir and remove the website link where.the logo is coming

**Comment by toshitapandey** [comment]
Cool. Picking it up then. :)

**Comment by MalloZup** [comment]
Nice thx

**Comment by MalloZup** [comment]
thank you!
