### ISSUE TITLE
Use PRs

### ISSUE THREAD

**Issue by juliogonzalez** [openSUSE/gitarro#45]
@MalloZup, can you please make a single PR for the refactor and transformation into a gem?

I am trying to add a new functionality, but I see now duplicated code, and don't know where to make the changes anymore.

**Comment by MalloZup** [comment]
@juliogonzalez  i will rebase it

**Comment by juliogonzalez** [comment]
Great, but don't do it on master!

What's already on master, should stay, or there will be conflicts for people who already cloned the repo.

Why we should be always develop and test with PRs and never send commits directly to openSUSE/gitarro.

**Comment by MalloZup** [comment]
@juliogonzalez yop,  i took the only exception for this renaming , consider it as fixed, sorry for this inconvenients, the gitbot -> gitarro took some time :)

**Comment by juliogonzalez** [comment]
I still see duplicated code, one at lib/ the other at gem/lib (for example), so when I try to rebase it is impossible to do it :-(

If the only valid code is under gem/ then we need git to make aware that we are moving things from / to gem/

**Comment by MalloZup** [comment]
everything in gem directory is not valid, (i updated right now the doc).

I will add a gitgnore now for gem dir

**Comment by juliogonzalez** [comment]
@MalloZup I have conflicts at my local master fetch from upstream (this repo)

Did you rebased master at this repo?

**Comment by juliogonzalez** [comment]
Basically I can see the following commits at one of my FIX branches with commits that are not at master anymore:

@MalloZup
MalloZup
Remove gitbot from classname
7eb82d5
 @MalloZup
MalloZup
Replace gitbot name class with simply backend
cacf8fe
 @MalloZup
MalloZup
Remove gitbot dependencies in libraries
de9b46f
 @MalloZup
MalloZup
Remove gitbot name in code
93fc2c3

**Comment by juliogonzalez** [comment]
@MalloZup never squash branches at master, because now the PR I have, an another one I was preparing need to be closed and I will need to prepare manual diffs since my branches do not share a common history with master anymore :-(

**Comment by MalloZup** [comment]
@juliogonzalez  ok , sorry . Consider this  as an exception that occurred because all this renaming stuff

**Comment by juliogonzalez** [comment]
No problem :-)

Just keep in mind that changing history at upstream (specially muster) must never be done, even if the history is dirty.

That's why we should use always PRs (or when working on repositories without other people, at least using branches and making clear to the people which branches are master or master-equivalent and which branches can change history).

**Comment by MalloZup** [comment]
@juliogonzalez ok thx for clarifications, normally i'm the PR fanatic too.

I think we should consider issue #42  asap.
 
This include the dockerimages, but what is more critical is that all our jenkins job are using the old name

```gitbot```

At moment we have a salt state that take the latest version of gitbot (cloned it) etc,

tomorrow i will fix the jobs via gui :cry:  ( this is why we need a jenkinsfile or something)

**Comment by MalloZup** [comment]
i close this

**Comment by juliogonzalez** [comment]
You can also fix the jobs via API with a bash script. Well have a look tomorrow.
