### ISSUE TITLE
changelogtest should be a separate standalone test ( not part of gitarro itself)

### ISSUE THREAD

**Issue by MalloZup** [openSUSE/gitarro#54]
Figure out how to extrapolate the whole changelog flag and make a standalone test that gitarro will execute like

-t `changelog.rb`

**Comment by MalloZup** [comment]
@juliogonzalez i think this --changelogtest option is kind of unrelated and is adding more complexity on the codebase

**Comment by juliogonzalez** [comment]
I agree.

We should maybe provide it inside the tools/ directory and then as an example.

**Comment by MalloZup** [comment]
@juliogonzalez  afaik, the simplest solution for this, imho would be to create a docker container from gitarro, and freeze this container with the version of gitarro containing the changelog test.

I had a look at the changelog tests and this is the simplest solution imho.

**Comment by juliogonzalez** [comment]
Let me see how the changelog test works right now and think a little about it, before we take a final decission.

**Comment by MalloZup** [comment]
@juliogonzalez  i have found a solution for this:

With this simply extrernal script:

´gitarro -t script´
```bash
git ls-tree --name-only -r HEAD^ | grep .changes .. etc
```

We can test if last commit changed the .changes file or not, which is what we want.

The only issue, is in case a PR doesn't need to modify the changelog.

**Comment by juliogonzalez** [comment]
I am not 100% sure, but I think it won't work if the PR has several commits and the changelog was not changed at the last commit.

**Comment by juliogonzalez** [comment]
I will have a look today, but IMHO we would need a simple ruby script to check GitHub API.

Since netrc will be already present, it should be easy to do it.

**Comment by MalloZup** [comment]
the only difficulty is that from  gitarro to the test_script, the test script doesn't know which PR number is tested (gitarro know that). 

If you use another script to use the github api, ( we will consume again rate limiting) :D .

**Comment by juliogonzalez** [comment]
Then most probably we need to refactor the changelog test to make the currenct code easier :-D

**Comment by MalloZup** [comment]
atm the changelogtest is so refactored that it disappear :)

**Comment by juliogonzalez** [comment]
Then maybe we will need to re-add it :-)
