### ISSUE TITLE
Refactor in smaller classes/modules Backend.lib

### ISSUE THREAD

**Issue by MalloZup** [openSUSE/gitarro#66]
At moment the class Backend.rb has to many responsabilities.

We need to split it, in more indipendant classes. (or modules)
- TestExecutor class ( where all test execution operation are done)
- StatusPr class (where we handle all status operation)

- Tasks:

- [x] https://github.com/openSUSE/gitarro/issues/54  remove changelog

- [x] #67 

- [x] 3

**Comment by juliogonzalez** [comment]
Given all the problems we are having with rubocop complaining about Backend.lib, we should consider the refactor a priority.
