### ISSUE TITLE
remove --C check optiont from gitarro, and create a /tools/gitarro_check.rb

### ISSUE THREAD

**Issue by MalloZup** [openSUSE/gitarro#79]
This options is mixing the behaviour.

We should have a test_executor and a trigger/scheduler (utilty/tools that is used on jenkins, for example)

**Comment by juliogonzalez** [comment]
As discussed online, I think we should keep it as a "dry run".

It will be easier to use and identify after we refactor :-)

**Comment by MalloZup** [comment]
ok maybe we will reopen it. :sunglasses:
