### ISSUE TITLE
Pass PR metadata to script executed

### ISSUE THREAD

**Issue by MalloZup** [openSUSE/gitarro#89]
it would be nice that the script can have some metadata about the PR that is running on

**Comment by dincamihai** [comment]
The most interesting port would be the PR name and author

**Comment by MalloZup** [comment]
ok this is not really difficult. we can export this variables in ENV, and then each script(python, ruby can use them)

**Comment by MalloZup** [comment]
@dincamihai  we can have all this variable
https://developer.github.com/v3/pulls/#get-a-single-pull-request

**Comment by MalloZup** [comment]
@dincamihai  ok i just created a PR wich adress this.

It works. atm i added only 3 VARS, Pr number, Pr author, and Pr Title.  I think we could ad td more but it easy use them.

Next week i will merge the PR

**Comment by MalloZup** [comment]
@juliogonzalez  feel free to make any suggestions for needed vars :sunflower:
